{vars, ...}: {
	home-manager.users.${vars.user.name}.programs.bat.themes.custom = ''
		<!-- https://github.com/sublimehq/Packages/blob/master/Color%20Scheme%20-%20Default/Monokai.sublime-color-scheme -->
		<plist version="1.0">
		  <dict>
		    <key>name</key>
		    <string>Custom Theme</string>
		    <key>settings</key>
		    <array>
		      <dict>
		        <key>settings</key>
		        <dict>
		          <key>background</key>
		          <string>${vars.theme.style.ui.bg}</string>
		          <key>caret</key>
		          <string>${vars.theme.style.text.main}</string>
		          <key>foreground</key>
		          <string>${vars.theme.style.text.main}</string>
		          <key>invisibles</key>
		          <string>${vars.theme.style.text.comment}</string>
		          <key>lineHighlight</key>
		          <string>${vars.theme.style.ui.overlay}</string>
		          <key>selection</key>
		          <string>${vars.theme.style.ui.overlay}</string>
		        </dict>
		      </dict>
		      <dict>
		        <key>name</key>
		        <string>Comment</string>
		        <key>scope</key>
		        <string>comment</string>
		        <key>settings</key>
		        <dict>
		          <key>foreground</key>
		          <string>${vars.theme.style.text.comment}</string>
		        </dict>
		      </dict>
		      <dict>
		        <key>name</key>
		        <string>String</string>
		        <key>scope</key>
		        <string>string</string>
		        <key>settings</key>
		        <dict>
		          <key>foreground</key>
		          <string>${vars.theme.style.text.syntax.string}</string>
		        </dict>
		      </dict>
		      <dict>
		        <key>name</key>
		        <string>Number</string>
		        <key>scope</key>
		        <string>constant.numeric</string>
		        <key>settings</key>
		        <dict>
		          <key>foreground</key>
		          <string>${vars.theme.style.text.syntax.number}</string>
		        </dict>
		      </dict>
		      <dict>
		        <key>name</key>
		        <string>Built-in constant</string>
		        <key>scope</key>
		        <string>constant.language</string>
		        <key>settings</key>
		        <dict>
		          <key>foreground</key>
		          <string>${vars.theme.style.text.syntax.number}</string>
		        </dict>
		      </dict>
		      <dict>
		        <key>name</key>
		        <string>User-defined constant</string>
		        <key>scope</key>
		        <string>constant.character, constant.other</string>
		        <key>settings</key>
		        <dict>
		          <key>foreground</key>
		          <string>${vars.theme.style.text.syntax.number}</string>
		        </dict>
		      </dict>
		      <dict>
		        <key>name</key>
		        <string>Variable</string>
		        <key>scope</key>
		        <string>variable</string>
		        <key>settings</key>
		        <dict>
		          <key>fontStyle</key>
		          <string></string>
		        </dict>
		      </dict>
		      <dict>
		        <key>name</key>
		        <string>Keyword</string>
		        <key>scope</key>
		        <string>keyword</string>
		        <key>settings</key>
		        <dict>
		          <key>foreground</key>
		          <string>${vars.theme.style.text.syntax.keyword}</string>
		        </dict>
		      </dict>
		      <dict>
		        <key>name</key>
		        <string>Storage</string>
		        <key>scope</key>
		        <string>storage</string>
		        <key>settings</key>
		        <dict>
		          <key>fontStyle</key>
		          <string></string>
		          <key>foreground</key>
		          <string>${vars.theme.style.text.syntax.keyword}</string>
		        </dict>
		      </dict>
		      <dict>
		        <key>name</key>
		        <string>Storage type</string>
		        <key>scope</key>
		        <string>storage.type</string>
		        <key>settings</key>
		        <dict>
		          <key>fontStyle</key>
		          <string>italic</string>
		          <key>foreground</key>
		          <string>${vars.theme.style.text.syntax.info}</string>
		        </dict>
		      </dict>
		      <dict>
		        <key>name</key>
		        <string>Class name</string>
		        <key>scope</key>
		        <string>entity.name.class</string>
		        <key>settings</key>
		        <dict>
		          <key>fontStyle</key>
		          <string>underline</string>
		          <key>foreground</key>
		          <string>${vars.theme.style.text.syntax.success}</string>
		        </dict>
		      </dict>
		      <dict>
		        <key>name</key>
		        <string>Inherited class</string>
		        <key>scope</key>
		        <string>entity.other.inherited-class</string>
		        <key>settings</key>
		        <dict>
		          <key>fontStyle</key>
		          <string>italic underline</string>
		          <key>foreground</key>
		          <string>${vars.theme.style.text.syntax.success}</string>
		        </dict>
		      </dict>
		      <dict>
		        <key>name</key>
		        <string>Function name</string>
		        <key>scope</key>
		        <string>entity.name.function</string>
		        <key>settings</key>
		        <dict>
		          <key>fontStyle</key>
		          <string></string>
		          <key>foreground</key>
		          <string>${vars.theme.style.text.syntax.function}</string>
		        </dict>
		      </dict>
		      <dict>
		        <key>name</key>
		        <string>Function argument</string>
		        <key>scope</key>
		        <string>variable.parameter</string>
		        <key>settings</key>
		        <dict>
		          <key>fontStyle</key>
		          <string>italic</string>
		          <key>foreground</key>
		          <string>${vars.theme.style.text.syntax.number}</string>
		        </dict>
		      </dict>
		      <dict>
		        <key>name</key>
		        <string>Tag name</string>
		        <key>scope</key>
		        <string>entity.name.tag</string>
		        <key>settings</key>
		        <dict>
		          <key>fontStyle</key>
		          <string></string>
		          <key>foreground</key>
		          <string>${vars.theme.style.text.syntax.keyword}</string>
		        </dict>
		      </dict>
		      <dict>
		        <key>name</key>
		        <string>Tag attribute</string>
		        <key>scope</key>
		        <string>entity.other.attribute-name</string>
		        <key>settings</key>
		        <dict>
		          <key>fontStyle</key>
		          <string></string>
		          <key>foreground</key>
		          <string>${vars.theme.style.text.syntax.success}</string>
		        </dict>
		      </dict>
		      <dict>
		        <key>name</key>
		        <string>Library function</string>
		        <key>scope</key>
		        <string>support.function</string>
		        <key>settings</key>
		        <dict>
		          <key>fontStyle</key>
		          <string></string>
		          <key>foreground</key>
		          <string>${vars.theme.style.text.syntax.info}</string>
		        </dict>
		      </dict>
		      <dict>
		        <key>name</key>
		        <string>Library constant</string>
		        <key>scope</key>
		        <string>support.constant</string>
		        <key>settings</key>
		        <dict>
		          <key>fontStyle</key>
		          <string></string>
		          <key>foreground</key>
		          <string>${vars.theme.style.text.syntax.info}</string>
		        </dict>
		      </dict>
		      <dict>
		        <key>name</key>
		        <string>Library class/type</string>
		        <key>scope</key>
		        <string>support.type, support.class</string>
		        <key>settings</key>
		        <dict>
		          <key>fontStyle</key>
		          <string>italic</string>
		          <key>foreground</key>
		          <string>${vars.theme.style.text.syntax.info}</string>
		        </dict>
		      </dict>
		      <dict>
		        <key>name</key>
		        <string>Library variable</string>
		        <key>scope</key>
		        <string>support.other.variable</string>
		        <key>settings</key>
		        <dict>
		          <key>fontStyle</key>
		          <string></string>
		        </dict>
		      </dict>
		      <dict>
		        <key>name</key>
		        <string>Invalid</string>
		        <key>scope</key>
		        <string>invalid</string>
		        <key>settings</key>
		        <dict>
		          <key>background</key>
		          <string>${vars.theme.style.text.syntax.error}</string>
		          <key>fontStyle</key>
		          <string></string>
		          <key>foreground</key>
		          <string>${vars.theme.style.ui.bg}</string>
		        </dict>
		      </dict>
		      <dict>
		        <key>name</key>
		        <string>Invalid deprecated</string>
		        <key>scope</key>
		        <string>invalid.deprecated</string>
		        <key>settings</key>
		        <dict>
		          <key>background</key>
		          <string>${vars.theme.style.text.syntax.keyword}</string>
		          <key>fontStyle</key>
		          <string></string>
		          <key>foreground</key>
		          <string>${vars.theme.style.ui.bg}</string>
		        </dict>
		      </dict>
		    </array>
		  </dict>
		</plist>
	'';
}
